version: '3.7'
services:
  web:
    container_name: web
    build: .
    ports:
     - "8015:80"
     - "443:443"
    volumes:
     - ./:/var/www/html
    links:
     - db_mysql
     - db_pgsql
     - db_pgsql_testing

  db_mysql:
    container_name: db_mysql
    image: mysql:5.7
    ports:
      - "33060:3306"
    volumes:
      - db_mysql_vol:/var/lib/mysql
    environment:
     - MYSQL_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=db_name

  db_pgsql:
    container_name: db_pgsql
    image: postgres
    ports:
      - "54322:5432"
    volumes:
      - db_pgsql_vol:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=root
     - POSTGRES_USER=root
     - POSTGRES_DB=db_name

  db_pgsql_testing:
    container_name: db_pgsql_testing
    image: postgres
    ports:
      - "54323:5432"
    volumes:
      - db_pgsql_testing_vol:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=root
     - POSTGRES_USER=root
     - POSTGRES_DB=db_name

volumes:
  db_mysql_vol:
  db_pgsql_vol:
  db_pgsql_testing_vol: