version: '3.7'
services:
  web:
    container_name: web
    build: './docker/php/'
    ports:
     - "8015:80"
     - "443:443"
    volumes:
     - ./:/var/www/html
    links:
     - db_pgsql

  db_pgsql:
    container_name: db_pgsql
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_pgsql_vol:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=root
     - POSTGRES_USER=root
     - POSTGRES_DB=db_name

volumes:
  db_pgsql_vol: